// <auto-generated />
namespace SCOTUS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class execremove : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(execremove));
        
        string IMigrationMetadata.Id
        {
            get { return "202104121755597_execremove"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
